### ISSUE TITLE
Re-build of the web interface (enhancing the looks of the UI)

### ISSUE THREAD

**Issue by fnadde42** [Hoglet/TimeIT-Server#3]
The interface is functional but a enhancement of the interface (even though it's low priority) is something that eventyally has to be done.

http://getbootstrap.com/

**Comment by Hoglet** [comment]
Before choosing technology it could be good to decide what you actually want to achieve. My previous exposure to bootsrap is negative so I am reluctant to choose it without serious evaluation.

To be clear, main goals of project is:
- Reliability
- Maintainability
- Functionality

Using Bootstrap or Foundation (or something else) could help creating a web application better suporting variety of browsers, especially on mobile phones. Considering the distributed aspect of timeit I think that it is better to put the effort in to an actual android (and ios) app which will have greater possibilities. 

PS:
"Choosing between Bootstrap or Foundation is like choosing between red or white wine". My question is: should we really drink alcohol?

Please add examples on what should be improved.

**Comment by Hoglet** [comment]
Closing as this does not describe a specific problem.
