### ISSUE TITLE
Task.completed and Time.comment

### ISSUE THREAD

**Issue by joonis** [Hoglet/TimeIT-Server#5]
What are the properties `Task.completed` and `Time.comment` used for?

Is it correct that all task and time records are just marked as deleted but never removed from the database?

**Comment by Hoglet** [comment]
Task.completed has no function and is removed in later revisions.

More answers in [Q & A](https://github.com/Hoglet/TimeIT-Server/wiki/Qustions-&-Answers)

**Comment by joonis** [comment]
> Q: Is it correct that all task and time records are just marked as deleted but never removed from the database?
> A: Yes. This is to ensure that there is no synchronisation error resurrecting a deleted item.

But all time records could be finally removed from database if the task itself was marked as deleted.

**Comment by Hoglet** [comment]
Agreed, that could be an improvement. At least if we do not want to implement any "undelete"

**Comment by Hoglet** [comment]
And, yes, a public discussion forum would be nice. I have a discord server here: [Hoglet's server](https://discord.gg/bXWHgXhg) if you, or anybody else, are interested in discussing and/or developing TimeIt. The discord server also contain my other projects, 3D printing, but it is a forum never the less.
